### ISSUE TITLE
feature: Eviction notification to Prometheus server

### ISSUE THREAD

**Issue by muthusamymm** [maksim-paskal/aks-node-termination-handler#12]
Any plans to add eviction event notification to Prometheus Server.

**Comment by maksim-paskal** [comment]
Hi @muthusamymm 

I will try to implement this feature in next release

**Comment by muthusamymm** [comment]
Thank you for considering my request,

Thanks,
Muthu

**Comment by maksim-paskal** [comment]
@muthusamymm standart way to push metrics to Prometheus - is using https://github.com/prometheus/pushgateway 

To resolve you issue you need to install pushgateway to your infrastucture and with next release you need to install `aks-node-termination-handler` with new arguments

```bash
-webhook.url=http://prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics/job/aks-node-termination-handler 
-webhook.template='node_termination_event{node="{{ .Node }}"} 1'
```

where `-webhook.url` is url to pushgateway endpoint and `-webhook.template` is template for building a message - you can  use for templating `{{ .Node }}` or any information about event `{{ .Event.EventId }}` more information about event information here https://docs.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events 

Is it OK to you?

**Comment by muthusamymm** [comment]
hi Maksim Paskal,

This is really good and yes it will solve the problem . I will integrate
pushgateway and let me know once this new release is available .

thanks,
Muthu

**Comment by maksim-paskal** [comment]
this feature released

Update or install your current installation
```bash
helm repo add aks-node-termination-handler https://maksim-paskal.github.io/aks-node-termination-handler/
helm repo update

helm upgrade aks-node-termination-handler \
--install \
--create-namespace \
--namespace aks-node-termination-handler \
aks-node-termination-handler/aks-node-termination-handler \
--set args[0]=-webhook.url=https://hooks.slack.com/services/ID/ID/ID \
--set args[1]=-telegram.token=<telegram token> \
--set args[2]=-telegram.chatID=<telegram chatid> \
--set args[3]=-webhook.url=http://prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics/job/aks-node-termination-handler \
--set args[4]=-webhook.template='node_termination_event{node="{{ .Node }}"} 1'
```

**Comment by muthusamymm** [comment]
Thank you Maksim Paskal for quick support.
Validated it, works good .

Thanks,
Muthu
