### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by yazbekhe** [maksim-paskal/aks-node-termination-handler#54]
hello,
what are the requirements to use this tool, for example do we need to activate the "Instance termination" in the scaleset of the aks pool? and if yes, how do you recommend to activate it? as with "az aks create" i do not see an option to do it.

**Comment by maksim-paskal** [comment]
Hi @yazbekhe, thanks for your question, I will try to figure out this parameter, by default this parameter I think is enabled, in my clusters I didn't force enabled this option

**Comment by maksim-paskal** [comment]
There is no need to enable instance termination notification on scale sets, according to [documentation](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-terminate-notification#get-terminate-notifications)

```
Scheduled Events is enabled for your scale set the first time you make a request for events. You can expect a delayed response in your first call of up to two minutes. Query the endpoint periodically to detect upcoming maintenance events and the status of ongoing maintenance activities.
```

When you start this pods in your cluster, pods will make request for events, and this will automatically enable instance termination notification.

For my clusters "Enable instance termination notification" on scale sets is always "Off" but events are received.

**Comment by yazbekhe** [comment]
thanks, it works

**Comment by yazbekhe** [comment]
yes you are right events are received but when a VM is being deleted it get deleted automatically which means it does not wait for confirmation before

**Comment by maksim-paskal** [comment]
I think it can be used in such way, by default, this pods run only on spot spot nodes and listens only events for spot instances, you can run this pods on all nodes of your cluster, and I think that this can handle events for all nodes of your cluster.

Please try this instalation:
```bash
helm upgrade aks-node-termination-handler \
--install \
--namespace kube-system \
aks-node-termination-handler/aks-node-termination-handler \
--set priorityClassName=system-node-critical \
--set nodeSelector=null
```
Let me know is it works for you

**Comment by yazbekhe** [comment]
no it does not work on noraml nodes, because the cluster autoscaler taint the node then delete it, and even if activate manually the instance termination on the scaleset i do not get any event on deletion. thanks for you help
